name: Test Xray Download

on:
  push:
  workflow_dispatch: # Allows you to manually trigger the button from the Actions tab

jobs:
  download-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Download and Unzip
        run: |
          wget -O "Xray-linux-64.zip" "https://github.com/XTLS/Xray-core/releases/download/v25.12.2/Xray-linux-64.zip"
          unzip Xray-linux-64.zip

      - name: List Contents
        run: |
          echo "Listing files..."
          ls -F *
